return {
  "stevearc/conform.nvim",
  optional = true,
  opts = {
    formatters_by_ft = {
      ["css"] = { "prettier" },
      ["scss"] = { "prettier" },
      ["javascript"] = { "prettier" },
      ["javascriptreact"] = { "prettier" },
      ["json"] = { "prettier" },
      ["jsonc"] = { "prettier" },
      ["less"] = { "prettier" },
      ["lua"] = { "stylua" },
      ["graphql"] = { "prettier" },
      ["handlebars"] = { "prettier" },
      ["html"] = { "prettier" },
      ["markdown"] = { "markdownlint" },
      ["markdown.mdx"] = { "markdownlint" },
      ["python"] = { "ruff", "black", "isort" },
      ["typescript"] = { "prettier" },
      ["typescriptreact"] = { "prettier" },
      ["vue"] = { "prettier" },
      ["yaml"] = { "prettier" },
    },
    format_on_save = {
      lsp_fallback = true,
      async = false,
      timeout_ms = 500,
    },
  },
}
